// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function ClearRecentFiles():Promise<void>;

export function CloseTab(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:string):Promise<void>;

export function GetRecentFiles():Promise<Array<main.RecentEntry>>;

export function GetTabPath(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function IsMarkdown(arg1:string):Promise<boolean>;

export function LoadFile(arg1:string):Promise<main.FileContent>;

export function OpenFile():Promise<main.FileContent>;

export function ResolveImagePaths(arg1:string,arg2:string):Promise<string>;
