// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetTabPath(arg1) {
  return window['go']['main']['App']['GetTabPath'](arg1);
}

export function IsMarkdown(arg1) {
  return window['go']['main']['App']['IsMarkdown'](arg1);
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function ResolveImagePaths(arg1, arg2) {
  return window['go']['main']['App']['ResolveImagePaths'](arg1, arg2);
}
